language: node_js
node_js:
- 6.10.3
dist: trusty
sudo: required
addons:
  chrome: stable # have Travis install chrome stable.
before_script:
  - npm install -g @angular/cli
install:
- npm install
script:
- npm test
